services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    container_name: backend_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENV: production
      DATABASE_URL_DOCKER: postgresql://postgres:postgres@postgres_db:5432/my_database
    ports:
      - "8000:8000"
    command: ["/bin/sh", "-c", "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
